<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

### Table of Contents

-   [alg](#alg)
-   [algCheckValid](#algcheckvalid)
-   [Circle](#circle)
    -   [id](#id)
    -   [type](#type)
    -   [points](#points)
    -   [addPoint](#addpoint)
    -   [center](#center)
    -   [h](#h)
    -   [k](#k)
    -   [r](#r)
    -   [eq](#eq)
    -   [toString](#tostring)
    -   [log](#log)
-   [Element](#element)
-   [Equation](#equation)
    -   [params](#params)
-   [Explorer](#explorer)
-   [Line](#line)
    -   [id](#id-1)
    -   [type](#type-1)
    -   [points](#points-1)
    -   [addPoint](#addpoint-1)
    -   [eq](#eq-1)
    -   [checkSegments](#checksegments)
    -   [toString](#tostring-1)
    -   [log](#log-1)
-   [Model](#model)
    -   [points](#points-2)
    -   [addPoint](#addpoint-2)
    -   [findPoint](#findpoint)
    -   [elements](#elements)
    -   [addElement](#addelement)
    -   [findElement](#findelement)
    -   [segments](#segments)
    -   [addSegment](#addsegment)
    -   [goldensections](#goldensections)
    -   [systems](#systems)
-   [Point](#point)
    -   [id](#id-2)
    -   [type](#type-2)
    -   [x](#x)
    -   [y](#y)
    -   [xVal](#xval)
    -   [yVal](#yval)
    -   [isValid](#isvalid)
    -   [parents](#parents)
    -   [addParent](#addparent)
    -   [distanceTo](#distanceto)
    -   [compare](#compare)
    -   [toString](#tostring-2)
    -   [log](#log-2)
-   [Section](#section)
-   [Segment](#segment)
    -   [id](#id-3)
    -   [type](#type-3)
    -   [points](#points-3)
    -   [length](#length)
    -   [lengthVal](#lengthval)
    -   [toString](#tostring-3)
-   [System](#system)
-   [View](#view)
    -   [PTRAD](#ptrad)
    -   [STROKEFACTOR](#strokefactor)
    -   [boundaryLines](#boundarylines)
    -   [addPoint](#addpoint-3)
-   [D](#d)
-   [main](#main)

## alg

shortcut for Algebrite.run see: <http://algebrite.org>

checks for valid result

**Parameters**

-   `cmd` **algCommand** Algebrite command string

**Examples**

```javascript
cmd = `c = ((${pt1.x}) * (${pt2.y})) - ((${pt2.x}) * (${pt1.y}))`
alg(cmd)
let c = alg(`c`)
```

Returns **algExpression** algebraic expression - nothing on error

## algCheckValid

check if algExpression string has `"Stop:"` or `"nil"`

**Parameters**

-   `str` **algExpression** Algebrite command string

Returns **[boolean](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean)** true or false

## Circle

represents a radial proportion between two points

**Parameters**

-   `cpt` **[Point](#point)** center point of the circle
-   `rpt` **[Point](#point)** radius point of the circle.

### id

id of the element - set by the context of the [Model](#model)<br>
usually the index in the elements array

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

### type

convenience type check for the element

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** "circle"

### points

an array of points on this element

does not include center point (not on the circle)

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** of [Point](#point)

### addPoint

add a point to this element's point list

usually called by the [Model](#model) to add intersection points

checks to determine if the point is already present

**Parameters**

-   `Point`  

Returns **[Point](#point)** 

### center

center point - set by constructor

Returns **[Point](#point)** 

### h

represents the x-offset in `(x - h)^2 + (y - k)^2 = r^2`

h = (${cpt.x})

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** algebraic value

### k

represents the y-offset in `(x - h)^2 + (y - k)^2 = r^2`

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** algebraic value

### r

represents the radius length in `(x - h)^2 + (y - k)^2 = r^2`

r = ( (cpt.x - rpt.x)^2 + (rpt.y - cpt.y)^2 )^(1/2)\`)

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** algebraic value

### eq

the equation associated with this element
set by constructor

`d x^2 + e x y + f y^2 + a x + b y = c`

`d = 1` // always for a circle <br>
`e = 0` // always for a circle <br>
`f = 1` // always for a circle <br>
`a = -2h` <br>
`b = -2k` <br>
`c = h^2 + k^2 - r^2` // but sign is changed to put it on the other side of the equals <br>

Returns **[Equation](#equation)** 

### toString

formatted string representing attribute of the circle

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

### log

grouped console output to represent the object<br>
perfect for logging

Returns **[console](https://developer.mozilla.org/docs/Web/API/Console)** 

## Element

Intended to be a parent class for the common properties of [Line](#line) and [Circle](#circle)

TODO: create a common Class of Element for Line and Circle

**Parameters**

-   `pt1` **[Point](#point)** initial point of the element
-   `pt2` **[Point](#point)** initial point of the element

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

## Equation

a set of parameters representing proportions for an element: [Line](#line) or [Circle](#circle)

uses a generalized form that supports both lines and circles

`d x^2 + e x y + f y^2 + a x + b y = c`

ensure that the sign of c is passed in correctly
can support other conic 2d forms in the future

the parameters are set as strings representing algebraic values <br>
these parameters are held as properties of an object so that the properties can be iterated through for analysis

algebrite provides all the calculations of the algebraic values and conversion to float when necessary

-   TODO:  Equation should be treated as a static immutable object
-   TODO: all values that don't change should be calculated on construction.

**Parameters**

-   `d` **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** coefficient for x^2 term - always 1 for a circle - 0 for line
-   `e` **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** coefficient for xy term - should always be zero in this model
-   `f` **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** coefficient for y^2 term - always 1 for a circle - 0 for line
-   `a` **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** coefficient for x term
-   `b` **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** coefficient for y term
-   `c` **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** constant - WATCH SIGN - note that we position the c value on the other side of the equations

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

### params

an object of parameters

can be iterated

**Examples**

```javascript
function nonZeroCoeffients() {
let count = 0;
for (var key in this.params) {
  // don't count the final constant
  if (key != 'c') {
    if (this.params[key] != 0) { count++ }
  }
}
return count
}
```

Returns **[Object](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object)** with properties for each coefficient

## Explorer

Controller for the [Model](#model) and [View](#view)

primary interface for [main](#main)

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

## Line

a linear proportion established by two points

constructor calculates linear proportions from the x, y values of the points recieved

TODO: points should be immutable after instantiation

**Parameters**

-   `pt1` **[Point](#point)** initial point of the line
-   `pt2` **[Point](#point)** initial point of the line.

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

### id

id of the element - set by the context of the [Model](#model)<br>
usually the index in the elements array

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

### type

convenience type check for the element

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** "line"

### points

an array of points on this element

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** of [Point](#point)

### addPoint

add a point to this element's point list
usually called by the [Model](#model) to add intersection points
checks to determine if the point is already present

**Parameters**

-   `Point`  

Returns **[Point](#point)** 

### eq

the equation associated with this element

-   set by constructor

d x^2 + e x y + f y^2 + a x + b y = c

d = 0 // always for a line <br>
e = 0 // always for a line <br>
f = 0 // always for a line <br>
a = (pt1.y) - (pt2.y) <br>
b = (pt2.x) - (pt1.x) <br>
c = ((pt1.x) _ (pt2.y)) - ((pt2.x) _ (pt1.y))   // but sign is changed to put it on the other side of the equals <br>

Returns **[Equation](#equation)** 

### checkSegments

check all pairs of contiguous segments on this line for golden ratio instances

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** collection of new [Section](#section) objects where `.isGoldenRatio = true`

### toString

formatted string representing properties of the line

good for logging

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

### log

grouped console output to represent the object

perfect for logging

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

## Model

a container for holding a sets of points, elements.
segments and other graphical elements may also be contained in the model

generally instantiated by Explorer

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

### points

the array of [Point](#point) objects within the Model

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** of [Point](#point)

### addPoint

add a [Point](#point) to the Model.points Array<br>
usually called to add new intersection points<br>
checks to determine if the newPoint is already in the Array - if so, returns exisitng point<br>

**Parameters**

-   `newPoint` **[Point](#point)** 

Returns **[Point](#point)** returns existing point if there is a match or new point if not

### findPoint

Find [Point](#point) in Model.points with a matching x, y

**Parameters**

-   `x` **algValue** 
-   `y` **algValue** 

Returns **[Point](#point)** returns existing point if there is a match

### elements

the array of [Element](#element) objects (Lines and Circles) within the Model

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** 

### addElement

add an [Element](#element) to the Model.elements Array
usually called after a valid Element is created
checks to determine if the Element is already present

**Parameters**

-   `newElement` **[Element](#element)** 

Returns **[Element](#element)** returns existing element if there is a match

### findElement

Find [Element](#element) in Model.elements with a matching equation parameters

TODO: complete this

**Parameters**

-   `x` **[Element](#element)** 
-   `y` **algValue** 

Returns **[Point](#point)** returns existing point if there is a match

### segments

the array of [Segment](#segment) along lines that are participating in golden sections

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** 

### addSegment

add a [Segment](#segment) to the Model.segments Array
usually called when the lengths of pair of segments are in the golden ratio
checks to determine if the point is already present

**Parameters**

-   `newSegment` **[Segment](#segment)** 

Returns **[Segment](#segment)** returns existing segment if there is a match

### goldensections

the array of [Section](#section) objects on a line that are in the golden ratio

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** 

### systems

the array of [System](#system) objects

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** 

## Point

represents a position within a two dimension cartesian plane - specified by two values

other than the two starting points, points are derived through the intersection of elements

TODO: points should be immutable after instantiation

**Parameters**

-   `x` **algValue** string with algebraic value
-   `y` **algValue** string with algebraic value
-   `parent1` **[Element](#element)** parent element - intersecting line or circle.
-   `parent2` **[Element](#element)** parent element - intersecting line or circle.

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

### id

id of the element - set by the context of the [Model](#model)<br>
usually the index in the elements array

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

### type

convenience type check for the element

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** "point"

### x

algebraic value - set by constructor

Returns **algValue** algebraic value

### y

algebraic value - set by constructor

Returns **algValue** algebraic value

### xVal

floating point value - set by constructor - converted from AlgValue

Returns **float** 

### yVal

floating point value - set by constructor - converted from AlgValue

Returns **float** 

### isValid

set to false if x or y are not a number

Returns **[boolean](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean)** 

### parents

an array of parent elements that this point lies on

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** of Elements

### addParent

add a point to this element's point list
usually called by the [Model](#model) to add intersection points
checks to determine if the point is already present

**Parameters**

-   `Point`  

Returns **[Point](#point)** 

### distanceTo

determine the distance from this point to the supplied point

**Parameters**

-   `Point`  

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** algebraic value

### compare

used for sorting points on a line

-   if this point is less than test point return -1
-   if this point is greater than test point return 1
-   return zero if equal

**Parameters**

-   `point` **[Point](#point)** to test

Returns **int** \-1, 0, 1

### toString

formatted string representing attribute of the object

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

### log

grouped console output to represent the object

perfect for logging

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

## Section

pair of segments
derives length for determining Golden Ratio instances

**Parameters**

-   `segment1` **[Segment](#segment)**  point on the line
-   `segment2` **[Segment](#segment)**  point on the line.

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

## Segment

-   represents the set of two points on a line<br>
-   derives length for determining _Golden Ratio_ instances

TODO: could be of type [Element](#element)

**Parameters**

-   `pt1` **[Point](#point)**  endpoint of the segment
-   `pt2` **[Point](#point)**  endpoint of the segment
-   `line` **[Line](#line)**  the line.

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

### id

id of the segment - set by the context of the [Model](#model)<br>
usually the index in the elements array

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

### type

convenience type check for the element

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** "line"

### points

an array of points on this segment - ordered

-   only two for a segment

Returns **[Array](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array)** of [Point](#point)

### length

algebraic value - set by constructor

Returns **algValue** algebraic value

### lengthVal

floating point value - set by constructor - converted from AlgValue

Returns **float** 

### toString

formatted string representing attribute of the circle

Returns **[string](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String)** 

## System

System - collection of equations - starting with two elements
provides a roots solution set - an array of objects with x, y values
should show all the work

**Parameters**

-   `element1` **[Element](#element)** first element
-   `element2` **[Element](#element)** second element

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

## View

a container for drawing and animating the SVG panel
and the other data panels of the UI

-   sets up boundary lines for the drawing

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT

### PTRAD

radius for point icon

### STROKEFACTOR

for variable width stroke on segments in proportion to the line length

### boundaryLines

Array of `Line` objects defining the boundary of the Drawing<br>

-   using these in `View.addLine` to determine the end points of [Line](#line) in the [model](model)
-   these lines are not added to the `Model.elements` array

### addPoint

add a [Point](#point) to the View<br>
SVG `circle` object representing the point location
radius of `circle` set by **`this.PTRAD`**

**Parameters**

-   `newPoint` **[Point](#point)** 

Returns **[svgElement](https://developer.mozilla.org/docs/Web/SVG/Element/animate)** `circle` object

## D

SVG Drawing

## main

main.js - script to sequence the creating and display of the geometric model

primary interface for [main](#main)

**Meta**

-   **author**: 𝚽 &lt;phi@geometor.com>
-   **license**: MIT
